<?php

return [

    'asset_tag'   	=> 'Инвертарный номер',
    'asset_model'       => 'Модель',
    'book_value'  	=> 'Текущее значение',
    'change' 		=> 'Отвязан/Привязан',
    'checkout_date' => 'Дата выдачи',
    'checkoutto' 	=> 'Выдан',
    'current_value' => 'Текущее значение',
    'diff' 			=> 'Разн',
    'dl_csv' 		=> 'Загрузить CSV',
    'eol' 			=> 'Истечение срока службы',
    'id'      		=> 'ID',
    'location' 		=> 'Географическое расположение',
    'purchase_cost'	=> 'Стоимость',
    'purchase_date'	=> 'Куплен',
    'serial'   		=> 'Серийный номер',
    'status'   		=> 'Статус',
    'title'      	=> 'Актив ',
    'image'		    => 'Изображение устройства',
    'days_without_acceptance' => 'Дней без принятия',
    'monthly_depreciation' => 'Ежемесячная амортизация',
    'assigned_to'    => 'Назначенный На',
    'requesting_user' => 'Запрашивающий пользователь',
    'requested_date' => 'Запрошенная дата',
    'changed'       => 'Измененный',
    'icon' => 'Значок',
];
