<?php

return [
    'about_locations_title'     => 'О расположениях',
    'about_locations'           => 'Географические расположения используются для отслеживания информации о месте нахождения пользователей, активов, и других предметов',
    'assets_rtd'                => 'Активы', // This has NEVER meant Assets Retired. I don't know how it keeps getting reverted.
    'assets_checkedout'         => 'Активы назначены',
    'id'                        => 'ID',
    'city'                      => 'Город',
    'state'                     => 'Область/Регион',
    'country'                   => 'Страна',
    'create'                    => 'Создать географическое расположение',
    'update'                    => 'Редактировать географическое расположение',
    'print_assigned'            => 'Печать выданного',
    'print_all_assigned'        => 'Печать всего выданного',
    'name'                      => 'Название географического расположения',
    'address'                   => 'Адрес',
    'zip'                       => 'Почтовый индекс',
    'locations'                 => 'Расположения',
    'parent'                    => 'Родитель',
    'currency'                  => 'Валюта географическое расположение',
    'ldap_ou'                   => 'Поиск в LDAP OU',
    'user_name'                 => 'Имя пользователя',
    'department'                => 'Подразделение',
    'location'                  => 'Расположение',
    'asset_tag'                 => 'Тег активов',
    'asset_name'                => 'Название',
    'asset_category'            => 'Категория',
    'asset_manufacturer'        => 'Производитель',
    'asset_model'               => 'Модель',
    'asset_serial'              => 'Серийный номер',
    'asset_location'            => 'Географическое расположение',
    'asset_checked_out'         => 'Проверено',
    'asset_expected_checkin'    => 'Ожидаемая проверка',
    'date'                      => 'Дата:',
    'signed_by_asset_auditor'   => 'Подписано (Аудитором активов):',
    'signed_by_finance_auditor' => 'Подписано (Аудитором активов):',
    'signed_by_location_manager' => 'Подписано (Руководитель географического расположения):',
    'signed_by'                 => 'Подписано:',
];
