version: '3'
services:
  mysql:
    env_file:
      - ./.env
    image: mysql:5.6
    restart: unless-stopped
    volumes:
      - snipeit-sql-vol:/var/lib/mysql
    networks:
      reverse-proxy-network:
        aliases:
          - snipeit-mysql
  snipeit:
    env_file:
      - ./.env
    image: snipe/snipe-it:v6.1.2
    restart: unless-stopped
    volumes:
      - snipeit-vol:/var/lib/snipeit
      #--------------------------------------------------------
      #RU localization mostly fixed, optional
      - ./ru:/var/www/html/resources/lang/ru
      #--------------------------------------------------------
      #GOOD:
      # Client <= HTTP => Reverse Proxy <= HTTP => Snipe-IT
      # or
      # Client <= HTTPS => Reverse Proxy <= HTTPS => Snipe-IT
      # 
      #BAD:
      # Client <= HTTPS => Reverse Proxy <= HTTP => Snipe-IT
      #source: https://snipe-it.readme.io/docs/reverse-proxies
      #so ceritifcate and key must be copied into following directory:
      - ./ssl:/var/lib/snipeit/ssl
      #--------------------------------------------------------
    networks:
      reverse-proxy-network:
        aliases:
          - snipeit
    depends_on:
      - mysql

networks:
  reverse-proxy-network:
     name: reverse-proxy-network
     external: true

volumes:
  snipeit-sql-vol:
  snipeit-vol:
